# c:\xampp\mysql\bin\mysql -uroot --default_character_set=utf8 < C:\Users\AMD\Documents\GitHub\ER-diagram-zadaci\ER_tesko\002-DAOS\DAOS.sql

-- MySQL Script generated by MySQL Workbench
-- Tue May 30 18:21:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DAOS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DAOS` ;

-- -----------------------------------------------------
-- Schema DAOS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DAOS` DEFAULT CHARACTER SET utf8 ;
USE `DAOS` ;

-- -----------------------------------------------------
-- Table `DAOS`.`matica_rodjenih`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`matica_rodjenih` (
  `idmatica_rodjenih` INT NOT NULL AUTO_INCREMENT,
  `datum_rodjena` DATE NOT NULL,
  PRIMARY KEY (`idmatica_rodjenih`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`matica_vjencanih`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`matica_vjencanih` (
  `idmatica_vjencanih` INT NOT NULL AUTO_INCREMENT,
  `datum_vjenjcanja` DATE NULL,
  PRIMARY KEY (`idmatica_vjencanih`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`matica_umrlih`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`matica_umrlih` (
  `idmatica_umrlih` INT NOT NULL AUTO_INCREMENT,
  `datum_smrti` DATE NOT NULL,
  PRIMARY KEY (`idmatica_umrlih`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`zupanija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`zupanija` (
  `idzupanija` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idzupanija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`osoba` (
  `idosoba` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `vjera` VARCHAR(45) NOT NULL,
  `matica_rodjenih_idmatica_rodjenih` INT NOT NULL,
  `matica_umrlih_idmatica_umrlih` INT NOT NULL,
  `matica_vjencanih_idmatica_vjencanih` INT NOT NULL,
  PRIMARY KEY (`idosoba`),
  INDEX `fk_osoba_matica_rodjenih1_idx` (`matica_rodjenih_idmatica_rodjenih` ASC),
  INDEX `fk_osoba_matica_umrlih1_idx` (`matica_umrlih_idmatica_umrlih` ASC),
  INDEX `fk_osoba_matica_vjencanih1_idx` (`matica_vjencanih_idmatica_vjencanih` ASC),
  CONSTRAINT `fk_osoba_matica_rodjenih1`
    FOREIGN KEY (`matica_rodjenih_idmatica_rodjenih`)
    REFERENCES `DAOS`.`matica_rodjenih` (`idmatica_rodjenih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_osoba_matica_umrlih1`
    FOREIGN KEY (`matica_umrlih_idmatica_umrlih`)
    REFERENCES `DAOS`.`matica_umrlih` (`idmatica_umrlih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_osoba_matica_vjencanih1`
    FOREIGN KEY (`matica_vjencanih_idmatica_vjencanih`)
    REFERENCES `DAOS`.`matica_vjencanih` (`idmatica_vjencanih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`korisnik` (
  `idkorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `oib` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkorisnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`zahtjev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`zahtjev` (
  `idzahtjev` INT NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `zahtjev` TEXT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `matica_vjencanih_idmatica_vjencanih` INT NOT NULL,
  `matica_umrlih_idmatica_umrlih` INT NOT NULL,
  `matica_rodjenih_idmatica_rodjenih` INT NOT NULL,
  PRIMARY KEY (`idzahtjev`),
  INDEX `fk_zahtjev_korisnik1_idx` (`korisnik_idkorisnik` ASC),
  INDEX `fk_zahtjev_matica_vjencanih1_idx` (`matica_vjencanih_idmatica_vjencanih` ASC),
  INDEX `fk_zahtjev_matica_umrlih1_idx` (`matica_umrlih_idmatica_umrlih` ASC),
  INDEX `fk_zahtjev_matica_rodjenih1_idx` (`matica_rodjenih_idmatica_rodjenih` ASC),
  CONSTRAINT `fk_zahtjev_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `DAOS`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjev_matica_vjencanih1`
    FOREIGN KEY (`matica_vjencanih_idmatica_vjencanih`)
    REFERENCES `DAOS`.`matica_vjencanih` (`idmatica_vjencanih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjev_matica_umrlih1`
    FOREIGN KEY (`matica_umrlih_idmatica_umrlih`)
    REFERENCES `DAOS`.`matica_umrlih` (`idmatica_umrlih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjev_matica_rodjenih1`
    FOREIGN KEY (`matica_rodjenih_idmatica_rodjenih`)
    REFERENCES `DAOS`.`matica_rodjenih` (`idmatica_rodjenih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DAOS`.`mjesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DAOS`.`mjesto` (
  `idmjesto` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `zupanija_idzupanija` INT NOT NULL,
  `matica_rodjenih_idmatica_rodjenih` INT NOT NULL,
  `matica_umrlih_idmatica_umrlih` INT NOT NULL,
  `matica_vjencanih_idmatica_vjencanih` INT NOT NULL,
  PRIMARY KEY (`idmjesto`),
  INDEX `fk_mjesto_zupanija_idx` (`zupanija_idzupanija` ASC),
  INDEX `fk_mjesto_matica_rodjenih1_idx` (`matica_rodjenih_idmatica_rodjenih` ASC),
  INDEX `fk_mjesto_matica_umrlih1_idx` (`matica_umrlih_idmatica_umrlih` ASC),
  INDEX `fk_mjesto_matica_vjencanih1_idx` (`matica_vjencanih_idmatica_vjencanih` ASC),
  CONSTRAINT `fk_mjesto_zupanija`
    FOREIGN KEY (`zupanija_idzupanija`)
    REFERENCES `DAOS`.`zupanija` (`idzupanija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjesto_matica_rodjenih1`
    FOREIGN KEY (`matica_rodjenih_idmatica_rodjenih`)
    REFERENCES `DAOS`.`matica_rodjenih` (`idmatica_rodjenih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjesto_matica_umrlih1`
    FOREIGN KEY (`matica_umrlih_idmatica_umrlih`)
    REFERENCES `DAOS`.`matica_umrlih` (`idmatica_umrlih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mjesto_matica_vjencanih1`
    FOREIGN KEY (`matica_vjencanih_idmatica_vjencanih`)
    REFERENCES `DAOS`.`matica_vjencanih` (`idmatica_vjencanih`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
