# c:\xampp\mysql\bin\mysql -uroot --default_character_set=utf8 < C:\Users\AMD\Documents\GitHub\ER-diagram-zadaci\ER_tesko\DVD.sql

-- MySQL Script generated by MySQL Workbench
-- Tue May 30 14:20:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DVD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DVD` ;

-- -----------------------------------------------------
-- Schema DVD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DVD` DEFAULT CHARACTER SET utf8 ;
USE `DVD` ;

-- -----------------------------------------------------
-- Table `DVD`.`dvd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`dvd` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dvd_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `DVD`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `dvd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_dvd1_idx` (`dvd_id` ASC),
  CONSTRAINT `fk_event_dvd1`
    FOREIGN KEY (`dvd_id`)
    REFERENCES `DVD`.`dvd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `news_name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `dvd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_dvd_idx` (`dvd_id` ASC),
  CONSTRAINT `fk_news_dvd`
    FOREIGN KEY (`dvd_id`)
    REFERENCES `DVD`.`dvd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dvd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_dvd1_idx` (`dvd_id` ASC),
  CONSTRAINT `fk_user_dvd1`
    FOREIGN KEY (`dvd_id`)
    REFERENCES `DVD`.`dvd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guest_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dvd_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guest_dvd1_idx` (`dvd_id` ASC),
  CONSTRAINT `fk_guest_dvd1`
    FOREIGN KEY (`dvd_id`)
    REFERENCES `DVD`.`dvd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`gallery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `path` VARCHAR(45) NULL,
  `gallery_id` INT NOT NULL,
  PRIMARY KEY (`id`, `gallery_id`),
  INDEX `fk_picture_gallery1_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_picture_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `DVD`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`gallery_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`gallery_has_news` (
  `gallery_id` INT NOT NULL,
  `news_id` INT NOT NULL,
  PRIMARY KEY (`gallery_id`, `news_id`),
  INDEX `fk_gallery_has_news_news1_idx` (`news_id` ASC),
  INDEX `fk_gallery_has_news_gallery1_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_gallery_has_news_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `DVD`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `DVD`.`news` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DVD`.`gallery_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DVD`.`gallery_has_event` (
  `gallery_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`gallery_id`, `event_id`),
  INDEX `fk_gallery_has_event_event1_idx` (`event_id` ASC),
  INDEX `fk_gallery_has_event_gallery1_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_gallery_has_event_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `DVD`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `DVD`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
