# c:\xampp\mysql\bin\mysql -uroot --default_character_set=utf8 < C:\Users\AMD\Documents\GitHub\ER-diagram-zadaci\ER_tesko\004-Koncerti\koncerti.sql


-- MySQL Script generated by MySQL Workbench
-- Tue May 30 19:47:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema koncerti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `koncerti` ;

-- -----------------------------------------------------
-- Schema koncerti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `koncerti` DEFAULT CHARACTER SET utf8 ;
USE `koncerti` ;

-- -----------------------------------------------------
-- Table `koncerti`.`posluzitelj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`posluzitelj` (
  `idposluzitelj` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idposluzitelj`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `koncerti`.`drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`drzava` (
  `iddrzava` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddrzava`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`koncert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`koncert` (
  `idkoncert` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `datum` DATE NULL,
  `drzava_iddrzava` INT NOT NULL,
  PRIMARY KEY (`idkoncert`),
  INDEX `fk_koncert_drzava1_idx` (`drzava_iddrzava` ASC),
  CONSTRAINT `fk_koncert_drzava1`
    FOREIGN KEY (`drzava_iddrzava`)
    REFERENCES `koncerti`.`drzava` (`iddrzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`izvodjac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`izvodjac` (
  `idizvodjac` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`idizvodjac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`korisnik` (
  `idkorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkorisnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`rezervacija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`rezervacija` (
  `idrezervacija` INT NOT NULL AUTO_INCREMENT,
  `korisnik_idkorisnik` INT NOT NULL,
  `koncert_idkoncert` INT NOT NULL,
  PRIMARY KEY (`idrezervacija`, `korisnik_idkorisnik`, `koncert_idkoncert`),
  INDEX `fk_rezervacija_korisnik1_idx` (`korisnik_idkorisnik` ASC),
  INDEX `fk_rezervacija_koncert1_idx` (`koncert_idkoncert` ASC),
  CONSTRAINT `fk_rezervacija_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `koncerti`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rezervacija_koncert1`
    FOREIGN KEY (`koncert_idkoncert`)
    REFERENCES `koncerti`.`koncert` (`idkoncert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`karta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`karta` (
  `idkarta` INT NOT NULL AUTO_INCREMENT,
  `rezervacija_idrezervacija` INT NOT NULL,
  `rezervacija_korisnik_idkorisnik` INT NOT NULL,
  PRIMARY KEY (`idkarta`, `rezervacija_idrezervacija`, `rezervacija_korisnik_idkorisnik`),
  INDEX `fk_karta_rezervacija1_idx` (`rezervacija_idrezervacija` ASC, `rezervacija_korisnik_idkorisnik` ASC),
  CONSTRAINT `fk_karta_rezervacija1`
    FOREIGN KEY (`rezervacija_idrezervacija` , `rezervacija_korisnik_idkorisnik`)
    REFERENCES `koncerti`.`rezervacija` (`idrezervacija` , `korisnik_idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`grad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`grad` (
  `idgrad` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `drzava_iddrzava` INT NOT NULL,
  PRIMARY KEY (`idgrad`, `drzava_iddrzava`),
  INDEX `fk_grad_drzava_idx` (`drzava_iddrzava` ASC),
  CONSTRAINT `fk_grad_drzava`
    FOREIGN KEY (`drzava_iddrzava`)
    REFERENCES `koncerti`.`drzava` (`iddrzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`dogadjaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`dogadjaj` (
  `iddogadjaj` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `datum` DATE NULL,
  `drzava_iddrzava` INT NOT NULL,
  PRIMARY KEY (`iddogadjaj`),
  INDEX `fk_dogadjaj_drzava1_idx` (`drzava_iddrzava` ASC),
  CONSTRAINT `fk_dogadjaj_drzava1`
    FOREIGN KEY (`drzava_iddrzava`)
    REFERENCES `koncerti`.`drzava` (`iddrzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`galerija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`galerija` (
  `idgalerija` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `dogadjaj_iddogadjaj` INT NOT NULL,
  PRIMARY KEY (`idgalerija`),
  INDEX `fk_galerija_dogadjaj1_idx` (`dogadjaj_iddogadjaj` ASC),
  CONSTRAINT `fk_galerija_dogadjaj1`
    FOREIGN KEY (`dogadjaj_iddogadjaj`)
    REFERENCES `koncerti`.`dogadjaj` (`iddogadjaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`fotografija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`fotografija` (
  `idfotografija` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `galerija_idgalerija` INT NOT NULL,
  PRIMARY KEY (`idfotografija`),
  INDEX `fk_fotografija_galerija1_idx` (`galerija_idgalerija` ASC),
  CONSTRAINT `fk_fotografija_galerija1`
    FOREIGN KEY (`galerija_idgalerija`)
    REFERENCES `koncerti`.`galerija` (`idgalerija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`dopisivanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`dopisivanje` (
  `iddopisivanje` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `posiljatelj` INT NOT NULL,
  `primatelj` INT NOT NULL,
  PRIMARY KEY (`iddopisivanje`, `posiljatelj`, `primatelj`),
  INDEX `fk_dopisivanje_korisnik1_idx` (`posiljatelj` ASC),
  INDEX `fk_dopisivanje_korisnik2_idx` (`primatelj` ASC),
  CONSTRAINT `fk_dopisivanje_korisnik1`
    FOREIGN KEY (`posiljatelj`)
    REFERENCES `koncerti`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dopisivanje_korisnik2`
    FOREIGN KEY (`primatelj`)
    REFERENCES `koncerti`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `koncerti`.`koncert_has_izvodjac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `koncerti`.`koncert_has_izvodjac` (
  `koncert_idkoncert` INT NOT NULL,
  `izvodjac_idizvodjac` INT NOT NULL,
  PRIMARY KEY (`koncert_idkoncert`, `izvodjac_idizvodjac`),
  INDEX `fk_koncert_has_izvodjac_izvodjac1_idx` (`izvodjac_idizvodjac` ASC),
  INDEX `fk_koncert_has_izvodjac_koncert1_idx` (`koncert_idkoncert` ASC),
  CONSTRAINT `fk_koncert_has_izvodjac_koncert1`
    FOREIGN KEY (`koncert_idkoncert`)
    REFERENCES `koncerti`.`koncert` (`idkoncert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_koncert_has_izvodjac_izvodjac1`
    FOREIGN KEY (`izvodjac_idizvodjac`)
    REFERENCES `koncerti`.`izvodjac` (`idizvodjac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
