# c:\xampp\mysql\bin\mysql -uroot --default_character_set=utf8 < C:\Users\AMD\Documents\GitHub\ER-diagram-zadaci\ER_tesko\006-cauliflower\cauliflower.sql

-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 17:01:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cauliflower
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cauliflower` ;

-- -----------------------------------------------------
-- Schema cauliflower
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cauliflower` DEFAULT CHARACTER SET utf8 ;
USE `cauliflower` ;

-- -----------------------------------------------------
-- Table `cauliflower`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cauliflower`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`seller` (
  `id_seller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seller`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `cauliflower`.`middleman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`middleman` (
  `id_middleman` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_middleman`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cauliflower`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`chat` (
  `id_chat` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `user_sender` INT NOT NULL,
  `user_recipient` INT NOT NULL,
  `seller_sender` INT NOT NULL,
  `seller_recipient` INT NOT NULL,
  `middleman_sender` INT NOT NULL,
  `middleman_recipient` INT NOT NULL,
  PRIMARY KEY (`id_chat`, `user_sender`, `user_recipient`, `seller_sender`, `seller_recipient`, `middleman_sender`, `middleman_recipient`),
  INDEX `fk_chat_user_idx` (`user_sender` ASC),
  INDEX `fk_chat_user1_idx` (`user_recipient` ASC),
  INDEX `fk_chat_seller1_idx` (`seller_sender` ASC),
  INDEX `fk_chat_seller2_idx` (`seller_recipient` ASC),
  INDEX `fk_chat_middleman1_idx` (`middleman_sender` ASC),
  INDEX `fk_chat_middleman2_idx` (`middleman_recipient` ASC),
  CONSTRAINT `fk_chat_user`
    FOREIGN KEY (`user_sender`)
    REFERENCES `cauliflower`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_user1`
    FOREIGN KEY (`user_recipient`)
    REFERENCES `cauliflower`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_seller1`
    FOREIGN KEY (`seller_sender`)
    REFERENCES `cauliflower`.`seller` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_seller2`
    FOREIGN KEY (`seller_recipient`)
    REFERENCES `cauliflower`.`seller` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_middleman1`
    FOREIGN KEY (`middleman_sender`)
    REFERENCES `cauliflower`.`middleman` (`id_middleman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_middleman2`
    FOREIGN KEY (`middleman_recipient`)
    REFERENCES `cauliflower`.`middleman` (`id_middleman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cauliflower`.`artwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`artwork` (
  `id_artwork` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `price` DECIMAL(18,2) NULL,
  `description` TEXT NULL,
  `seller_id_seller` INT NOT NULL,
  PRIMARY KEY (`id_artwork`),
  INDEX `fk_artwork_seller1_idx` (`seller_id_seller` ASC),
  CONSTRAINT `fk_artwork_seller1`
    FOREIGN KEY (`seller_id_seller`)
    REFERENCES `cauliflower`.`seller` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cauliflower`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cauliflower`.`photo` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `file_path` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `artwork_id_artwork` INT NOT NULL,
  PRIMARY KEY (`id_photo`, `artwork_id_artwork`),
  INDEX `fk_photo_artwork1_idx` (`artwork_id_artwork` ASC),
  CONSTRAINT `fk_photo_artwork1`
    FOREIGN KEY (`artwork_id_artwork`)
    REFERENCES `cauliflower`.`artwork` (`id_artwork`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
